# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cpu_model=None, cpu_mhz=None, cpu_cores=None):  # noqa: E501
        """InlineResponse2005 - a model defined in OpenAPI

        :param cpu_model: The cpu_model of this InlineResponse2005.  # noqa: E501
        :type cpu_model: str
        :param cpu_mhz: The cpu_mhz of this InlineResponse2005.  # noqa: E501
        :type cpu_mhz: float
        :param cpu_cores: The cpu_cores of this InlineResponse2005.  # noqa: E501
        :type cpu_cores: int
        """
        self.openapi_types = {
            'cpu_model': str,
            'cpu_mhz': float,
            'cpu_cores': int
        }

        self.attribute_map = {
            'cpu_model': 'cpu_model',
            'cpu_mhz': 'cpu_mhz',
            'cpu_cores': 'cpu_cores'
        }

        self._cpu_model = cpu_model
        self._cpu_mhz = cpu_mhz
        self._cpu_cores = cpu_cores

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cpu_model(self):
        """Gets the cpu_model of this InlineResponse2005.


        :return: The cpu_model of this InlineResponse2005.
        :rtype: str
        """
        return self._cpu_model

    @cpu_model.setter
    def cpu_model(self, cpu_model):
        """Sets the cpu_model of this InlineResponse2005.


        :param cpu_model: The cpu_model of this InlineResponse2005.
        :type cpu_model: str
        """

        self._cpu_model = cpu_model

    @property
    def cpu_mhz(self):
        """Gets the cpu_mhz of this InlineResponse2005.


        :return: The cpu_mhz of this InlineResponse2005.
        :rtype: float
        """
        return self._cpu_mhz

    @cpu_mhz.setter
    def cpu_mhz(self, cpu_mhz):
        """Sets the cpu_mhz of this InlineResponse2005.


        :param cpu_mhz: The cpu_mhz of this InlineResponse2005.
        :type cpu_mhz: float
        """

        self._cpu_mhz = cpu_mhz

    @property
    def cpu_cores(self):
        """Gets the cpu_cores of this InlineResponse2005.


        :return: The cpu_cores of this InlineResponse2005.
        :rtype: int
        """
        return self._cpu_cores

    @cpu_cores.setter
    def cpu_cores(self, cpu_cores):
        """Sets the cpu_cores of this InlineResponse2005.


        :param cpu_cores: The cpu_cores of this InlineResponse2005.
        :type cpu_cores: int
        """

        self._cpu_cores = cpu_cores
