# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uname=None):  # noqa: E501
        """InlineResponse2002 - a model defined in OpenAPI

        :param uname: The uname of this InlineResponse2002.  # noqa: E501
        :type uname: str
        """
        self.openapi_types = {
            'uname': str
        }

        self.attribute_map = {
            'uname': 'uname'
        }

        self._uname = uname

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uname(self):
        """Gets the uname of this InlineResponse2002.


        :return: The uname of this InlineResponse2002.
        :rtype: str
        """
        return self._uname

    @uname.setter
    def uname(self, uname):
        """Sets the uname of this InlineResponse2002.


        :param uname: The uname of this InlineResponse2002.
        :type uname: str
        """

        self._uname = uname
