# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total_memory=None, available_memory=None, free_memory=None):  # noqa: E501
        """InlineResponse2003 - a model defined in OpenAPI

        :param total_memory: The total_memory of this InlineResponse2003.  # noqa: E501
        :type total_memory: int
        :param available_memory: The available_memory of this InlineResponse2003.  # noqa: E501
        :type available_memory: int
        :param free_memory: The free_memory of this InlineResponse2003.  # noqa: E501
        :type free_memory: int
        """
        self.openapi_types = {
            'total_memory': int,
            'available_memory': int,
            'free_memory': int
        }

        self.attribute_map = {
            'total_memory': 'total_memory',
            'available_memory': 'available_memory',
            'free_memory': 'free_memory'
        }

        self._total_memory = total_memory
        self._available_memory = available_memory
        self._free_memory = free_memory

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_memory(self):
        """Gets the total_memory of this InlineResponse2003.


        :return: The total_memory of this InlineResponse2003.
        :rtype: int
        """
        return self._total_memory

    @total_memory.setter
    def total_memory(self, total_memory):
        """Sets the total_memory of this InlineResponse2003.


        :param total_memory: The total_memory of this InlineResponse2003.
        :type total_memory: int
        """

        self._total_memory = total_memory

    @property
    def available_memory(self):
        """Gets the available_memory of this InlineResponse2003.


        :return: The available_memory of this InlineResponse2003.
        :rtype: int
        """
        return self._available_memory

    @available_memory.setter
    def available_memory(self, available_memory):
        """Sets the available_memory of this InlineResponse2003.


        :param available_memory: The available_memory of this InlineResponse2003.
        :type available_memory: int
        """

        self._available_memory = available_memory

    @property
    def free_memory(self):
        """Gets the free_memory of this InlineResponse2003.


        :return: The free_memory of this InlineResponse2003.
        :rtype: int
        """
        return self._free_memory

    @free_memory.setter
    def free_memory(self, free_memory):
        """Sets the free_memory of this InlineResponse2003.


        :param free_memory: The free_memory of this InlineResponse2003.
        :type free_memory: int
        """

        self._free_memory = free_memory
