# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, date=None):  # noqa: E501
        """InlineResponse2001 - a model defined in OpenAPI

        :param date: The date of this InlineResponse2001.  # noqa: E501
        :type date: str
        """
        self.openapi_types = {
            'date': str
        }

        self.attribute_map = {
            'date': 'date'
        }

        self._date = date

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def date(self):
        """Gets the date of this InlineResponse2001.


        :return: The date of this InlineResponse2001.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this InlineResponse2001.


        :param date: The date of this InlineResponse2001.
        :type date: str
        """

        self._date = date
