# coding: utf-8

"""
    Practice API for Learning Swagger

    Practice API for Learning Swagger  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: marshall@theonsruds.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InlineResponse2003(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'total_memory': 'int',
        'available_memory': 'int',
        'free_memory': 'int'
    }

    attribute_map = {
        'total_memory': 'total_memory',
        'available_memory': 'available_memory',
        'free_memory': 'free_memory'
    }

    def __init__(self, total_memory=None, available_memory=None, free_memory=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse2003 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._total_memory = None
        self._available_memory = None
        self._free_memory = None
        self.discriminator = None

        if total_memory is not None:
            self.total_memory = total_memory
        if available_memory is not None:
            self.available_memory = available_memory
        if free_memory is not None:
            self.free_memory = free_memory

    @property
    def total_memory(self):
        """Gets the total_memory of this InlineResponse2003.  # noqa: E501


        :return: The total_memory of this InlineResponse2003.  # noqa: E501
        :rtype: int
        """
        return self._total_memory

    @total_memory.setter
    def total_memory(self, total_memory):
        """Sets the total_memory of this InlineResponse2003.


        :param total_memory: The total_memory of this InlineResponse2003.  # noqa: E501
        :type: int
        """

        self._total_memory = total_memory

    @property
    def available_memory(self):
        """Gets the available_memory of this InlineResponse2003.  # noqa: E501


        :return: The available_memory of this InlineResponse2003.  # noqa: E501
        :rtype: int
        """
        return self._available_memory

    @available_memory.setter
    def available_memory(self, available_memory):
        """Sets the available_memory of this InlineResponse2003.


        :param available_memory: The available_memory of this InlineResponse2003.  # noqa: E501
        :type: int
        """

        self._available_memory = available_memory

    @property
    def free_memory(self):
        """Gets the free_memory of this InlineResponse2003.  # noqa: E501


        :return: The free_memory of this InlineResponse2003.  # noqa: E501
        :rtype: int
        """
        return self._free_memory

    @free_memory.setter
    def free_memory(self, free_memory):
        """Sets the free_memory of this InlineResponse2003.


        :param free_memory: The free_memory of this InlineResponse2003.  # noqa: E501
        :type: int
        """

        self._free_memory = free_memory

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2003):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2003):
            return True

        return self.to_dict() != other.to_dict()
